### ISSUE TITLE
How the repository was cloned? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/vaspparser#4]
Commands:
```
git clone git@github.com:pyiron/pyiron_atomistics.git pyiron_vasp
cd pyiron_vasp
git remote rm origin
git filter-repo --path pyiron_atomistics/vasp --path pyiron_atomistics/dft --path tests/vasp --path tests/static/vasp --path tests/static/vasp_test_files --path CHANGELOG.md --path CITATION.cff --path CODE_OF_CONDUCT.md --path CONTRIBUTING.rst --path LICENSE --path MANIFEST.in --path README.md --path pyproject.toml --path setup.py --path .ci_support --path .coveralls.yml --path .github --force
git remote add origin git@github.com:pyiron/pyiron_vasp.git
git push --set-upstream origin main --force
```

**Comment by liamhuber** [comment]
What is the bug here? What even is the question?

Also, it looks like this was created using the `pyiron_module_template` -- but why bother when all of the module infrastructure provided by the template (main level config files, `.ci_support/*`, `.github/*`, ...) is just going to be overwritten by a force-push?

It's unclear what would be a resolution to the issue as posted.

**Comment by jan-janssen** [comment]
At the moment it is just for documentation.
